# apply 阶段生成 Yatta 独立管理的 sshd drop-in。任何校验失败都必须停止并回滚，
# 避免把远程登录入口留在半修改状态。
content="# Yatta managed SSH hardening. Do not edit this file directly.
"
expected_pairs=()
changed="0"

yatta_ssh_add_directive() {
  local key="$1"
  local value="$2"
  local effective_key="${3:-${key,,}}"
  content+="${key} ${value}"$'\n'
  expected_pairs+=("${effective_key}=${value}")
  changed="1"
}

if [[ "${YATTA_SSH_SET_PORT:-0}" == "1" ]]; then
  if ! yatta_valid_port "${YATTA_SSH_TARGET_PORT:-}"; then
    yatta_log_error "SSH 目标端口无效，已停止。"
    return 1
  fi
  yatta_ssh_add_directive "Port" "$YATTA_SSH_TARGET_PORT" "port"
fi

if [[ "${YATTA_SSH_SET_PERMIT_ROOT_LOGIN:-0}" == "1" ]]; then
  case "${YATTA_SSH_PERMIT_ROOT_LOGIN:-}" in
    no | prohibit-password) yatta_ssh_add_directive "PermitRootLogin" "$YATTA_SSH_PERMIT_ROOT_LOGIN" "permitrootlogin" ;;
    *) yatta_log_error "PermitRootLogin 目标值无效，已停止。"; return 1 ;;
  esac
fi

if [[ "${YATTA_SSH_SET_PASSWORD_AUTHENTICATION:-0}" == "1" ]]; then
  case "${YATTA_SSH_PASSWORD_AUTHENTICATION:-}" in
    yes | no) yatta_ssh_add_directive "PasswordAuthentication" "$YATTA_SSH_PASSWORD_AUTHENTICATION" "passwordauthentication" ;;
    *) yatta_log_error "PasswordAuthentication 目标值无效，已停止。"; return 1 ;;
  esac
fi

if [[ "${YATTA_SSH_SET_KBD_INTERACTIVE_AUTHENTICATION:-0}" == "1" ]]; then
  case "${YATTA_SSH_KBD_INTERACTIVE_AUTHENTICATION:-}" in
    yes | no) yatta_ssh_add_directive "KbdInteractiveAuthentication" "$YATTA_SSH_KBD_INTERACTIVE_AUTHENTICATION" "kbdinteractiveauthentication" ;;
    *) yatta_log_error "KbdInteractiveAuthentication 目标值无效，已停止。"; return 1 ;;
  esac
fi

if [[ "${YATTA_SSH_SET_PUBKEY_AUTHENTICATION:-0}" == "1" ]]; then
  case "${YATTA_SSH_PUBKEY_AUTHENTICATION:-}" in
    yes | no) yatta_ssh_add_directive "PubkeyAuthentication" "$YATTA_SSH_PUBKEY_AUTHENTICATION" "pubkeyauthentication" ;;
    *) yatta_log_error "PubkeyAuthentication 目标值无效，已停止。"; return 1 ;;
  esac
fi

if [[ "${YATTA_SSH_SET_PERMIT_EMPTY_PASSWORDS:-0}" == "1" ]]; then
  case "${YATTA_SSH_PERMIT_EMPTY_PASSWORDS:-}" in
    yes | no) yatta_ssh_add_directive "PermitEmptyPasswords" "$YATTA_SSH_PERMIT_EMPTY_PASSWORDS" "permitemptypasswords" ;;
    *) yatta_log_error "PermitEmptyPasswords 目标值无效，已停止。"; return 1 ;;
  esac
fi

if [[ "${YATTA_SSH_SET_MAX_AUTH_TRIES:-0}" == "1" ]]; then
  if [[ ! "${YATTA_SSH_MAX_AUTH_TRIES:-}" =~ ^[0-9]+$ ]] || ((YATTA_SSH_MAX_AUTH_TRIES < 1 || YATTA_SSH_MAX_AUTH_TRIES > 10)); then
    yatta_log_error "MaxAuthTries 目标值无效，已停止。"
    return 1
  fi
  yatta_ssh_add_directive "MaxAuthTries" "$YATTA_SSH_MAX_AUTH_TRIES" "maxauthtries"
fi

if [[ "${YATTA_SSH_SET_LOGIN_GRACE_TIME:-0}" == "1" ]]; then
  if [[ ! "${YATTA_SSH_LOGIN_GRACE_TIME:-}" =~ ^[0-9]+$ ]] || ((YATTA_SSH_LOGIN_GRACE_TIME < 10 || YATTA_SSH_LOGIN_GRACE_TIME > 300)); then
    yatta_log_error "LoginGraceTime 目标值无效，已停止。"
    return 1
  fi
  yatta_ssh_add_directive "LoginGraceTime" "$YATTA_SSH_LOGIN_GRACE_TIME" "logingracetime"
fi

if [[ "${YATTA_SSH_SET_X11_FORWARDING:-0}" == "1" ]]; then
  case "${YATTA_SSH_X11_FORWARDING:-}" in
    yes | no) yatta_ssh_add_directive "X11Forwarding" "$YATTA_SSH_X11_FORWARDING" "x11forwarding" ;;
    *) yatta_log_error "X11Forwarding 目标值无效，已停止。"; return 1 ;;
  esac
fi

if [[ "$changed" != "1" ]]; then
  yatta_log_info "没有需要应用的 SSH 加固配置。"
  return 0
fi

yatta_install_sshd_hardening_config "$content" "${expected_pairs[@]}" || return 1
yatta_reload_ssh_service
